services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tasksdb}
      POSTGRES_USER: ${POSTGRES_USER:-tasks}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tasks}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tasks} -d ${POSTGRES_DB:-tasksdb}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      LOG_LEVEL: info
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://tasks:tasks@db:5432/tasksdb}
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ["/bin/sh", "-c", "./entrypoint.sh"]
    volumes:
      - ./docs/specs:/app/docs/specs:ro

volumes:
  pgdata:
